---
name: Terraform CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  AWS_REGION: "us-east-1"
  EKS_CLUSTER_NAME: "ce-grp-2-dev-ce-grp-2-eks"
  TERRAFORM_VERSION: "1.7.4"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

# Checks code before applying

    - name: Terraform fmt
      run: terraform fmt -check

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
   
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact

    # - name: Checkov
    #   uses: bridgecrewio/checkov-action@master
    #   with:
    #     framework: terraform

    - name: Terraform Init
      run: terraform init
       
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

   

